name: Test React Frontend

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Running Tests...
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Navigate to directory
      - run: cd webapp
      - name: Install Dependencies
      - run: npm install
      - name: Run tests
      - run: npm run test
