name: Test React Frontend

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  unit-tests:
    name: Running Tests...
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.5"
      - name: Install dependencies
        working-directory: ./webapp
        run: npm install --force
      - name: Run tests
        working-directory: ./webapp
        run: npm run test
        
